/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static String subsequences(String word) {

        if (word.isEmpty()) {
            return "";
        } else {
            char firstLetter = word.charAt(0);
            String restOfWord = word.substring(1);

            String subsequencesOfRest = subsequences(restOfWord);

            String result = "";

            for (String subsequence : subsequencesOfRest.split(",", -1)) {
                result += "," + subsequence;
                result += "," + firstLetter + subsequence;
            }

            result = result.substring(1);
            return result;
        }



//        TODO: Make it real;
//        return word;
    }

    public static String subsequences1(String word) {
        return subsequencesAfter("", word);
    }

    private static String subsequencesAfter(String s, String word) {
        if (word.isEmpty()) {

            return s;
        } else {

        }
    }
}
